class Constants:
    """constants used throughout the code"""
    asset_key = "image"
    src_key = "src"
    href_key = "href"
    title_key = "title"
    resolution_key = "resolution"
    filename_key = "filename"
    dataset_key = "dataset"
    hits_key = "hits"
    """specific to elasticsearch"""
    source_key = "_source"
    project_key = "project"
    abstract_key = "abstract"
    creators_key = "creators"
    creator_key = "creator"
    datatables_key = "dataTables"
    attribute_list_key = "attributeList"
    attribute_name_key = "attributeName"
    keywords_kpi = "keywordsKpi"
    keyword_set_key = "keywordSet"
    keyword_key = "keyword"
    contact_key = "contact"
    contacts_key = "contacts"
    metadata_provider_key = "metadataProvider"
    license_url_key = "url_licensed_dataset"
    license_name_key = "licenseName_licensed_dataset"
    intellectual_rights_key = "intellectualRights_dataset"
    methods_key = "methods"
    method_steps_key = "methodSteps"
    citation_key = "citation"
    email_key = "email"
    electronic_email_address_key = "electronicMailAddress"
    individual_name_given_name_key = "individualNameGivenName"
    individual_name_surname_key = "individualNameSurName"
    organization_name_key = "organizationName"
    individual_name_key = "individualName"
    given_name_key = "givenName"
    surname_key = "surName"
    user_id_key = "userId"
    max_nbr_tokens = 4
    token_separator = "_"
    TIF_EXTENSION = "tif"
    isric_base_url = "https://isric.org/"
    soilgrids_base_url = "https://files.isric.org/soilgrids/latest/data_aggregated"
    geonetwork_base_url = "https://metadatacatalogue.lifewatch.eu"
    # this returns an elasticsearch payload, with encoding issues
    geonetwork_query_path_old = "/srv/api/records?uuid="
    # this is better for encoding
    geonetwork_query_path = "/srv/api/records/"
    # formatting
    geonetwork_query_path_format = "/formatters/json"
    geonetwork_name = "LifeWatch ERIC Metadata Catalogue"
    soilgrids_dataset_uuid = "8315df49-bde3-4138-8f71-9b722f3afd06"
    timeout = 30
    elastic_value = "elastic"
    eml_value = "eml"
    DEFAULT_PROJECTION = "EPSG:4326"
    BDOD_VALUE = "bdod"
    CEC_VALUE = "cec"
    CFVO_VALUE = "cfvo"
    CLAY_VALUE = "clay"
    NITROGEN_VALUE = "nitrogen"
    OCD_VALUE = "ocd"
    OCS_VALUE = "ocs"
    PHH2O_VALUE = "phh2o"
    SAND_VALUE = "sand"
    SILT_VALUE = "silt"
    SOC_VALUE = "soc"
    WV0010_VALUE = "wv0010"
    WV0033_VALUE = "wv0033"
    WV1500_VALUE = "wv1500"
    VARIABLE_NAMES = [BDOD_VALUE, CEC_VALUE, CFVO_VALUE, CLAY_VALUE, NITROGEN_VALUE, OCD_VALUE, OCS_VALUE, PHH2O_VALUE,
                      SAND_VALUE, SILT_VALUE, SOC_VALUE, WV0010_VALUE, WV0033_VALUE, WV1500_VALUE]
    band_names = ["0-5cm", "5-15cm", "15-30cm", "30-60cm", "60-100cm", "100-200cm", "0-30cm"]
    RESOLUTION_1000 = "1000"
    RESOLUTION_5000 = "5000"
    RESOLUTIONS = [RESOLUTION_1000, RESOLUTION_5000]
    BMD_PROJECT = "Biodiversity Meets Data (BMD) Project"
    BMD_DOI = "https://doi.org/10.3030/101181294"
    SIB_NAME = "Swiss Institute of Bioinformatics"
    SIB_URL = "https://www.sib.swiss"
